### ISSUE TITLE
resetApp functionality doesn't reset app state

### ISSUE THREAD

**Issue by SrinivasanTarget** [appium/appium-ios-driver#111]
I have logged into app and then tried to call resetApp() which actually installs the same app but i still see the app is in logged in state after reset is called.

https://gist.github.com/SrinivasanTarget/73c881423b82045373ec

Please let me know for more details.

Appium: 1.5 src
Node: 5.7.0
Java_client: 3.4.0

Haven't tried this in Appium 1.4.16.Will update the same for 1.4.16 in sometime.

https://github.com/appium/java-client/issues/332#issuecomment-193912915

@imurchie FYI

**Comment by MEZISH** [comment]
Same issue as #6206

**Comment by imurchie** [comment]
Yes. Currently, if you don't have `fullReset` set, `reset` doesn't do a full reset. Whether this is the best thing or not is arguable.

**Comment by rokly** [comment]
@imurchie fullReset does not work on real devices with appium 1.5.0
see [https://github.com/appium/appium/issues/6206#issuecomment-197201333](url)

**Comment by williamrussell-grindr** [comment]
@imurchie Places like DeviceFarm do not allow for the full reset cap. I wish the behavior between appium 1.4 and appium 1.5 was the same for this scenario.

**Comment by rkavalap** [comment]
Issue moved to [appium/appium #7413](https://github.com/appium/appium/issues/7413) via [**ZenHub**](https://www.zenhub.com/)
