### ISSUE TITLE
appium-ios-driver always check SafariLauncher.app on build folder even it's installed on device

### ISSUE THREAD

**Issue by nghiadhd** [appium/appium-ios-driver#119]
Prerequisite:
- SafariLauncher is installed on device

Actual behavior
- appium-ios-driver throws exception and exits the test

Expected behavior
- appium-ios-driver should check existing SafariLauncher on device before checking SafariLauncher.app on build folder

Environment:
- Real iPhone 6
- iOS 9.2.1
- Appium 1.5.0

Log:
- https://gist.github.com/nghiadhd/87072b7e154dd9a5c5c2500faf0e3bb7#file-ios-appium-log

**Comment by imurchie** [comment]
True. That should be the case. Working on it.

**Comment by imurchie** [comment]
Fixed in 3.7.1.

**Comment by nghiadhd** [comment]
Woe, so fast
Thank for your supporting

**Comment by imurchie** [comment]
My apologies. The fix is published in `appium-ios-driver@1.11.0`. If you are running from source you ought to be able update it there. If you are running from npm, you can re-install, adding the `--no-shrinkwrap` flag to get the latest.
