### ISSUE TITLE
Install flow needs to be examined

### ISSUE THREAD

**Issue by imurchie** [appium/appium-ios-driver#141]
In particular, installing an `ipa` file on a real device repeats steps and bypasses the checks for reset/no reset. This needs to be examined.

See https://github.com/appium/appium-ios-driver/pull/139#discussion_r61896077

**Comment by rkavalap** [comment]
Issue moved to [appium/appium #7414](https://github.com/appium/appium/issues/7414) via [**ZenHub**](https://www.zenhub.com/)
