### ISSUE TITLE
Swipe works incorrect. WaitAction is not perform

### ISSUE THREAD

**Issue by HlebHalkouski** [appium/appium-ios-driver#150]
Fast swipe, different behavior with Android.

## Environment
* Appium version (or git revision) that exhibits the issue: 1.5.2
* Last Appium version that did not exhibit the issue (if applicable): 1.4.16
* Desktop OS/version used to run Appium: Mac OS
* Node.js version (unless using Appium.app|exe): v5.7.0
* Mobile platform/version under test: iOS
* Real device or emulator/simulator: real 
* Appium CLI or Appium.app|exe: CLI

[Link to Appium logs](https://gist.github.com/HlebHalkouski/b745e1da71177a3f54b92e587ecd589a)

On javaclient@4.0.0 call method IOSDriver.swipe(200, 200, 0, 100, 3)

**Comment by imurchie** [comment]
What is the difference in behaviour? The log you sent is doing exactly what it is intended to do for that touch action.

**Comment by HlebHalkouski** [comment]
@imurchie 
Actual logic on iOS:
Pressed on the starting position, wait delay, jerk moved to the final location. What the investigation has led to the scrolls with inertia.

on Android:
Pressed on the starting position, and moved to the final position for a few seconds

**Comment by imurchie** [comment]
By "for a few seconds" you mean the scroll takes a few seconds?

**Comment by HlebHalkouski** [comment]
@imurchie I mean what action 'moveTo' takes few second. But on ios this action performs fast and result is scroll is larger than expected

**Comment by toejough** [comment]
I've discovered the same thing with the python client (v0.22).  

When calling `driver.swipe(from_x, from_y, to_x, to_y, duration)` with a long `duration`, say 1000 ms:
* appium server 1.4.x behavior: a swipe was performed, starting at the `from_` coordinates, ending at the `to_` coordinates, and taking `duration` ms to smoothly make that transition, as if a user had spent `duration` ms smoothly swiping from the `from_` to the `to_`.
* appium server 1.5.x behavior: a long-press is performed at the `from_` coordinates, lasting `duration` ms, followed by a flick to the `to_` coordinates (taking no ms).

Depending on the capabilities of the app screen currenly on, this causes any of:
* a super-delayed quick flick, scrolling far more than intended
* a long-press action
* both - a long-press action followed by a quick-flick

**Comment by toejough** [comment]
Appium 1.4.16, Python-client 0.22:
```
info: --> POST /wd/hub/session/d20267f5-0c92-48c8-8d78-b8fc72ad531e/touch/perform {"sessionId":"d20267f5-0c92-48c8-8d78-b8fc72ad531e","actions":[{"options":{"y":437,"x":134},"action":"press"},{"options":{"ms":500},"action":"wait"},{"options":{"y":437,"x":272},"action":"moveTo"},{"options":{},"action":"release"}]}
info: [debug] Pushing command to appium work queue: "au.dragApp(134,437,272,437,0.5)"
info: [debug] Sending command to instruments: au.dragApp(134,437,272,437,0.5)
info: [debug] [INST] 2016-07-11 19:37:44 +0000 Debug: Got new command 56 from instruments: au.dragApp(134,437,272,437,0.5)
info: [debug] [INST] 2016-07-11 19:37:44 +0000 Debug: evaluating au.dragApp(134,437,272,437,0.5)
info: [debug] [INST] 2016-07-11 19:37:44 +0000 Debug: target.dragFromToForDuration({x:"134", y:"437"}, {x:"272", y:"437"}, "0.5")
info: [debug] [INST] 2016-07-11 19:37:45 +0000 Debug: evaluation finished
info: [debug] [INST] 2016-07-11 19:37:45 +0000 Debug: responding with:
info: [debug] [INST] 2016-07-11 19:37:45 +0000 Debug: Running system command #57: /usr/local/Cellar/node/5.1.0/bin/node /usr/local/lib/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":""}...
info: [debug] Socket data received (25 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":""}
info: [debug] Responding to client with success: {"status":0,"value":"","sessionId":"d20267f5-0c92-48c8-8d78-b8fc72ad531e"}
info: <-- POST /wd/hub/session/d20267f5-0c92-48c8-8d78-b8fc72ad531e/touch/perform 200 1714.787 ms - 74 {"status":0,"value":"","sessionId":"d20267f5-0c92-48c8-8d78-b8fc72ad531e"}
```

**Comment by toejough** [comment]
Appium 1.5.3, Python-client 0.22:

```
[HTTP] --> POST /wd/hub/session/cb6d4f7d-6f2c-404d-8c3e-cabaa794edfa/touch/perform {"sessionId":"cb6d4f7d-6f2c-404d-8c3e-cabaa794edfa","actions":[{"action":"press","options":{"x":134,"y":437}},{"action":"wait","options":{"ms":500}},{"action":"moveTo","options":{"x":138,"y":0}},{"action":"release","options":{}}]}
[MJSONWP] Calling AppiumDriver.performTouch() with args: [[{"action":"press","option...
[debug] [iOS] Executing iOS command 'performTouch'
[debug] [UIAuto] Sending command to instruments: target.touch([{"touch":[{"x":134,"y":437}],"time":0.2},{"touch":[{"x":134,"y":437}],"time":0.7},{"touch":[{"x":272,"y":437}],"time":0.8999999999999999}])
[debug] [Instruments] [INST] 2016-07-11 19:46:09 +0000 Debug: Got new command 55 from instruments: target.touch([{"touch":[{"x":134,"y":437}],"time":0.2},{"touch":[{"x":134,"y":437}],"time":0.7},{"touch":[{"x":272,"y":437}],"time":0.8999999999999999}])
[debug] [Instruments] [INST] 2016-07-11 19:46:09 +0000 Debug: evaluating target.touch([{"touch":[{"x":134,"y":437}],"time":0.2},{"touch":[{"x":134,"y":437}],"time":0.7},{"touch":[{"x":272,"y":437}],"time":0.8999999999999999}])
[debug] [Instruments] [INST] 2016-07-11 19:46:09 +0000 Debug: target.touch(__NSCFArray)
[debug] [UIAuto] Socket data received (25 bytes)
[debug] [UIAuto] Got result from instruments: {"status":0,"value":""}
[MJSONWP] Responding to client with driver.performTouch() result: null
[HTTP] <-- POST /wd/hub/session/cb6d4f7d-6f2c-404d-8c3e-cabaa794edfa/touch/perform 200 15819 ms - 76
```

**Comment by toejough** [comment]
I tried to work around with the sequence of commands given in the [issue linked above](https://github.com/appium/java-client/issues/436), (longpress -> moveTo-> release -> perform), but no luck.  See my comment on https://github.com/appium/appium/pull/6153, which I found while searching for other such workarounds.

**Comment by toejough** [comment]
@imurchie - any further comment on this?  I found where the old drag code was [removed](https://github.com/appium/appium/commit/3da51d05cf6aa8a29e11ed94b0495d1d510dabf2) from appium, and am going to see if I can bring the old drag functionality back in a fork.  Let me know if I'm barking up the wrong tree, or if there's an upcoming fix already in the works :-)

**Comment by imurchie** [comment]
Yes please! If you can get it working (it should just be a matter of checking for the correct sequence, `press, wait, moveto, release`, and shunting the call off to a dedicated `drag` method in [this method](https://github.com/appium/appium-ios-driver/blob/master/lib/commands/gesture.js#L117)). I don't have time to do it at the moment, unfortunately.

I also don't see where it was done in the old (i.e., 1.4.x) system. Weird.

**Comment by toejough** [comment]
PR submitted - happy to update code/commit-message/unit-tests as directed, but swiping is now working for me when testing our iOS app!
