### ISSUE TITLE
Error converting element ID when element returned inside of a JSON object

### ISSUE THREAD

**Issue by mfulton26** [appium/appium-ios-driver#173]
When I return a web element as the result of a JavaScript script then I am able to use it fine (e.g. invoke `click`, `getTagName`, etc.). However, if I return some web element(s) inside of a result object then trying to use one results in "Error converting element ID for using in WD atoms".

The below example works for Chrome, Firefox, Android, etc. but not for iPhone via Appium:

```java
package com.example;

import org.openqa.selenium.Capabilities;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.Map;

@SuppressWarnings("unchecked")
public class FindElementByJavaScriptDemo {
    public static void main(String... args) throws MalformedURLException {
        WebDriver webDriver = createWebDriver();
        try {
            webDriver.get("https://www.google.com/");
            JavascriptExecutor javascriptExecutor = (JavascriptExecutor) webDriver;
            Object result = javascriptExecutor.executeScript("return {" +
                    "    element: document.getElementById('lst-ib') " +
                    "}");
            Map<String, ?> object = (Map<String, ?>) result;
            WebElement webElement = (WebElement) object.get("element");
            System.out.println(webElement.getTagName());
        } finally {
            webDriver.quit();
        }
    }

    private static RemoteWebDriver createWebDriver() throws MalformedURLException {
        return new RemoteWebDriver(createRemoteAddress(), createDesiredCapabilities());
    }

    private static URL createRemoteAddress() throws MalformedURLException {
        String username = System.getenv("SAUCE_USERNAME");
        String accessKey = System.getenv("SAUCE_ACCESS_KEY");
        String host = "ondemand.saucelabs.com:80";
        return new URL("http://" + username + ":" + accessKey + "@" + host + "/wd/hub");
    }

    private static Capabilities createDesiredCapabilities() {
        DesiredCapabilities desiredCapabilities = DesiredCapabilities.iphone();
        desiredCapabilities.setCapability("appiumVersion", "1.5.3");
        desiredCapabilities.setCapability("deviceName", "iPhone Simulator");
        desiredCapabilities.setCapability("deviceOrientation", "portrait");
        desiredCapabilities.setCapability("platformVersion", "9.3");
        desiredCapabilities.setCapability("platformName", "iOS");
        desiredCapabilities.setCapability("browserName", "Safari");
        return desiredCapabilities;
    }
}
```

```
Exception in thread "main" org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error converting element ID for using in WD atoms: :wdc:1472078050978 (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 110 milliseconds
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'NTISP138', ip: '192.168.56.1', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_60'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities [{orientation=PORTRAIT, networkConnectionEnabled=false, noReset=true, webdriver.remote.quietExceptions=true, hasMetadata=true, keepKeyChains=true, databaseEnabled=false, deviceName=iPhone Simulator, launchTimeout=180000, platform=MAC, backendRetries=4, showIOSLog=true, desired={showIOSLog=true, orientation=PORTRAIT, noReset=true, newCommandTimeout=0, platformVersion=9.3, webdriver.remote.quietExceptions=true, browserName=safari, keepKeyChains=true, platformName=iOS, deviceName=iPhone Simulator, launchTimeout=180000, backendRetries=4}, webdriver.remote.sessionid=10bf17df6e8149d88b1d5fbabbbf9da9, newCommandTimeout=0, platformVersion=9.3, locationContextEnabled=false, webStorageEnabled=false, takesScreenshot=true, browserName=safari, javascriptEnabled=true, platformName=iOS}]
Session ID: 10bf17df6e8149d88b1d5fbabbbf9da9
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:327)
	at org.openqa.selenium.remote.RemoteWebElement.getTagName(RemoteWebElement.java:144)
	at com.example.FindElementByJavaScriptDemo.main(FindElementByJavaScriptDemo.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by imurchie** [comment]
Can you provide the server logs? As a [gist](https://gist.github.com)?

**Comment by mfulton26** [comment]
[server logs for appium/appium-ios-driver issue #173](https://gist.github.com/mfulton26/5c193ecc3635fa1d1d677a7db3133b65)

**Comment by mfulton26** [comment]
@imurchie Will you please provide an update on this? Should the server logs I provided help? Thanks.

**Comment by jlipps** [comment]
@mfulton26 the reason is that the element ID returned by your call to execute script is not an Appium element id, it is a webdriver atoms element id. So Appium itself doesn't know anything about it. This can probably be fixed somehow, but first, what is the reason you are retrieving elements using executeScript instead of one of the regular find methods?

**Comment by mfulton26** [comment]
Thank you for the reply @jlipps. 

> @mfulton26 the reason is that the element ID returned by your call to execute script is not an Appium element id, it is a webdriver atoms element id. So Appium itself doesn't know anything about it.

If I execute `return document.getElementById('lst-ib');` using `WebDriver.executeScript` then I can successfully interact with the returned `WebElement` (i.e. I can call `getTagName()`, etc. without getting an error).
If I execute `return { element: document.getElementById('lst-ib') };` and unpack the `WebElement` returned in the object result then I cannot successfully interact with it (like in my example code I provided earlier).
Interestingly enough, if I execute `return [document.getElementById('lst-ib')];` and get the first element of the array/list it also works fine.

i.e. There doesn't appear to be an issue with returning elements via JavaScript in general but only when it is a property of an object.

Does appium-ios-driver have logic to walk JavaScript object trees and appropriately serialize elements? e.g. I'd like to be able to return something like `{ foo: { bar: { element: e }, baz: false } }` in which case the element is inside of a nested object.

--

In my real script I'm not using `getElementById` or anything similar to the standard WebDriver API methods (id, linkText, name, xpath, etc.). I'm using the CSS Box Model to return an tree of objects representing the visible boxes along with their displayed content which includes elements and strings of text.

**Comment by jlipps** [comment]
Thanks for the explanation @mfulton26. I think the issue is indeed that we don't have generic recursive element replacement in objects returned from the atoms. As you can see in the logic here: https://github.com/appium/appium-ios-driver/blob/master/lib/commands/web.js#L409-L439

We basically account for the possibilities of the element being returned itself or in an array, not nested inside an object.

I don't see why we wouldn't accept a PR that fixed it though! The only issue is that there could be a collision with an object that has an ELEMENT key that isn't actually a Selenium element. Guess that's probably not very likely.

**Comment by mfulton26** [comment]
I don't have a Mac and I am guessing that without one I won't be able to test my change end-to-end so I'm not sure I'd be able to do a PR. Please advise. Thank you.

**Comment by jlipps** [comment]
OK, linked it to appium/appium, and will close here. It's in our list to work on, but prioritized below other things since we're trying to get a release out.
