### ISSUE TITLE
What property should I set in stead of "fullReset" when I'd like to set "fullRest"?

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium-ios-driver#186]
Does "Cannot set preferences because a full-reset was requested" mean we should set `full-reset` as capability instead of `fullReset` ?
When I try to run Appium1.6.0 beta2 x iOS9.3(simulator) x xcuitest-driver with "fullRest" capability, then the following error caused and relaunch simulator many times(and stop running tests)

```
Error: Cannot set preferences because a full-reset was requested
```
( my full log is here: https://gist.github.com/KazuCocoa/e525f3fe7baf26bb7ed33dfbb1a8e437 )

According to the following line, I guess I should set full-reset instead of "fullReset". but when I set fill-reset as capability, the test app doesn't uninstall and re-install correctly.

- https://github.com/appium/appium-ios-driver/blob/2bfc4873ee330123739c6c7a430d2ebe0d6e30cc/lib/settings.js#L70

```js
async function setPreferences (sim, opts, safari = false) {
  let needToSetPrefs = checkPreferences(SETTINGS_CAPS, opts);
  let needToSetSafariPrefs = checkPreferences(SAFARI_SETTINGS_CAPS, opts);
  if (!needToSetPrefs && !needToSetSafariPrefs) {
    logger.debug("No iOS / app preferences to set");
    return;
  } else if (opts.fullReset) {
    let msg = "Cannot set preferences because a full-reset was requested";
    logger.errorAndThrow(msg);
  }

  logger.debug("Setting iOS and app preferences");

  if (await sim.isFresh()) {
    await launchAndQuitSimulator(sim, safari);
  }
```

**Comment by KazuCocoa** [comment]
In my case, I remove this lines and run test with `fullReset` capability, then my tests pass.

```js
 else if (opts.fullReset) {
    let msg = "Cannot set preferences because a full-reset was requested";
    logger.errorAndThrow(msg);
  }
```

**Comment by imurchie** [comment]
`full-reset` does not exist. That log line is just saying that a full reset was requested.

**Comment by KazuCocoa** [comment]
Thanks for quick response !

I set `fullReset` capability in this case like the following quote. The quote comes from my attached log. => https://gist.github.com/KazuCocoa/e525f3fe7baf26bb7ed33dfbb1a8e437 

> [HTTP] --> POST /wd/hub/session {"desiredCapabilities":{"platformVersion":"9.3","deviceName":"iPhone 4s","calendarFormat":"japanese","app":"/User/my_name/my_appium/script/xcode-builds/ios-my-app-build/Build/Products/Production-sandbox-autotest-iphonesimulator/my-app.app","bundleId":"com.my-app","automationName":"XCUITest","platformName":"iOS","sendKeyStrategy":"grouped","localizableStringsDir":"ja.lproj","language":"ja","locale":"ja_JP","screenshotWaitTimeout":5,"showIOSLog":false,"locationServicesEnabled":true,"waitForAppScript":"true;","newCommandTimeout":120,"fullReset":true}}

But `Error: Cannot set preferences because a full-reset was requested` was caused. In this case, was this error expected behaviour ?

**Comment by imurchie** [comment]
That is the expected behaviour. I'm trying out changing it to allow the two to co-exist.

**Comment by KazuCocoa** [comment]
Thanks a lot !
