### ISSUE TITLE
executeMobile 'scroll'

### ISSUE THREAD

**Issue by scottdixon** [appium/appium-ios-driver#30]
@imurchie, please see TODO:
https://github.com/appium/appium-ios-driver/blob/master/lib/commands/execute.js#L71-L79

AFAICT from https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/touch-actions.md scroll is the only supported command - please confirm.

**Comment by SrinivasanTarget** [comment]
@imurchie @scottdixon "mobile: swipe" works fine for me in current appium version.May i know why there is no support for the same in appium-ios-driver. Please clarify. If there could be a support shall i look into this?

**Comment by imurchie** [comment]
All of the `mobile` commands other than `mobile: scroll` were deprecated in 1.4 and removed in 1.5. The touch action API is better for these actions.
