### ISSUE TITLE
Find an AdmZip alternative

### ISSUE THREAD

**Issue by scottdixon** [appium/appium-ios-driver#35]
https://github.com/appium/appium-ios-driver/blob/master/lib/commands/file-movement.js#L97-L117

**Comment by Jonahss** [comment]
also used here: https://github.com/appium/appium-base-driver/blob/a7272db9498e77144331fd32ce8cfc46779d95c0/lib/helpers.js#L9

**Comment by rkavalap** [comment]
Issue moved to [appium/appium #7409](https://github.com/appium/appium/issues/7409) via [**ZenHub**](https://www.zenhub.com/)
